### ISSUE TITLE
Does ejs-grid keeps rowstate when deleting or modifying the record?

### ISSUE THREAD

**Issue by yiquanchaoren** [syncfusion/ej2-grids#12]
I am starting to use syncfusion angular version, can you answer one of my question?
When the ejs-grid delete a record by clicking the delete button of toolbar, will the datasource record the rowstate in web? If I want to record the delete rowstate, how should I do?

**Comment by renjithsingh-rajendran123** [comment]
Hi yiquanchaoren, 

Thanks for contacting Syncfusion support. 

We suspect that your requirement is to save the records which are removed from the Grid by using the toolbar delete action, to an array. We suggest you to use the “actionComplete” event of Grid. In the argument of the actionComplete event method you will be getting the current deleted record data. Based on the “requestType” as “delete” we suggest you to store the deleted record inside the array, by using this event. Please refer the code example below, 

`let grid: Grid = new Grid({ `
`        ... `
 `      toolbar: ["Add", "Delete", "Update"], `
`        actionComplete: complete, `
`        editSettings: { allowEditing: true, allowAdding: true, allowDeleting: true }, `
`        ... `
`   }); `
`    grid.appendTo('#Grid'); `
 
`    function complete(args: any) { `
`       if (args.requestType == "delete") { `
`            //Here in “args.data” you will be getting the deleted record data `
 `       } `
`    } `

Documentation : https://ej2.syncfusion.com/documentation/grid/api-grid.html?lang=es5#actioncomplete 
 
If we have misunderstood your query. Please get back to us with a detailed explanation of your complete requirement. Share a graphical representation to show your exact requirement. 

Regards, 
Renjith Singh Rajendran.
