### ISSUE TITLE
Does not show filter control in column header when column has template

### ISSUE THREAD

**Issue by oxxa** [syncfusion/ej2-grids#2]
In header-cell-renderer.ts there is this [line ](https://github.com/syncfusion/ej2-grids/blob/0bbc67d55f48cf6460c6388ceb63e11a186e9b25/src/grid/renderer/header-cell-renderer.ts#L94)

` (column.allowFiltering && isNullOrUndefined(column.template)) &&`

which seems to prevent the filtermenudiv being added to the headercell if it is a template column.  Is there a technical reason why this is done?  I have a template column (just showing the value in cells as <a href="#foo">{{data.foo}}</a>) and I would like to allow the user to filter on the field value of that column but no filter menu icon shows.  Please see http://plnkr.co/edit/Eplq8bSh8Rq2BmRJvPGX?p=preview  where you can see the missing filter icon on the 'Customer Name' column.

**Comment by pavithra95subramaniam** [comment]
Hi Oxxa,

Thanks for contacting Syncfusion support.

We have analyzed your query and we can reproduce the issue. We have considered this ‘Filtermenu with template column’ as a bug and logged a report for the same. The fix will be available  in our  November 23, 2017 release.
 
Regards,  
Pavithra S.
