### ISSUE TITLE
columnMenuClick event does not fired

### ISSUE THREAD

**Issue by Eretik** [syncfusion/ej2-grids#5]
I have tried to add Custom Column Menu Item to the Grid and my own handler for it. But columnMenuClick event does not fired at all, even example from documentation (http://ej2.syncfusion.com/15.4.23/documentation/grid/columns.html?lang=typescript#custom-column-menu-item) does not works. Could you please provide a fix for that?

**Comment by Eretik** [comment]
As I could see, the root cause of this issue - wrong constant of action name in /grid/base/constant.ts file. Now it is
`export const columnMenuClick: string = 'contextMenuClick';`
but should be
`export const columnMenuClick: string = 'columnMenuClick';`

**Comment by RamdhasUeikattan** [comment]
Hi Eretik,

Thanks for your interest in syncfusion products.

We have already fixed the reported issue and we have a patch release on January 10, 2018. The solution for the “**wrong constant name columnMenuClick**” will be available in this release (**Essential JS2 Grid v15.4.24**).

Regards,
Ramdhas  Ueikattan

**Comment by Eretik** [comment]
thanks a lot for the fix
