### ISSUE TITLE
Export fails when column has no associated field

### ISSUE THREAD

**Issue by oxxa** [syncfusion/ej2-grids#7]
**Bug:** 
Grid will not export successfully when one of the columns contains for example an image rather than a value from the datasource.

**Example:**
 http://plnkr.co/edit/Senp2L1lMECOEgHrgapz?p=preview

**Cause**
https://github.com/syncfusion/ej2-grids/blob/fac8f1df6e04e975a642ff3d2fee052bf5fccf74/src/grid/actions/excel-export.ts#L387

Now headerRow is all the grid's columns (except those with visible=false), but the bug arises when a column - as in the example above - does not have a 'field' property defined.  Now when 'getValue' function is called it cannot cope with null as argument to its namespace parameter and an error occurs leading to a silent failure to export.

**Fix Proposal**
Either..
1. check if the column has 'field' property before adding it to headerRow
2. or expose a 'shouldExport' property for e-column and take account of it in https://github.com/syncfusion/ej2-grids/blob/fac8f1df6e04e975a642ff3d2fee052bf5fccf74/src/grid/actions/export-helper.ts#L56
3. fix the getValue function to catch situation when passed null||undefined as a parameter and return null and then handle that in excel-export side so that column is not exported.

**Workaround**
For the moment I can set `<e-column field=''`  then the export will work but it exports a blank column.  I would like the option to either export the contents of the column as shown on screen (ie in the example the images) or else I would like to be able to choose not to export those columns at all.

**Comment by Pavithra15** [comment]
Hi Oxxa, 

We have checked your query and we have confirmed ‘Exporting throws script error for columns without field’ as a defect and logged a report for the same. The fix will be available in our February 14, 2018, release. Please use your workaround for the template column until then.  

However, you can hide the template column on export by setting the column.visible property as false before calling the export method. And then you have to set the column.visible property as true in promise.then() function of exporting method to restore the visible property. Please refer to the following code example and sample link. 
 
[component.ts] 

 `toolbarClick(args: ClickEventArgs): void { 
        switch (args.item.text) { 
            case 'PDF Export': 
                this.grid.getColumns()[0].visible = false; 
                this.grid.pdfExport().then(((e) => this.grid.getColumns()[0].visible = true)); 
                break; 
    } 
} `

Sample: http://plnkr.co/edit/fL5IUaZazaz5ZzkBSJ4c?p=preview  

Regards, 

Pavithra S.

**Comment by Pavithra15** [comment]
Hi @oxxa ,
 
We are glad to announce that our Essential JavaScript 2 patch release ([v 15.4.30](https://www.npmjs.com/~syncfusionorg)) is rolled out successfully and In that release, we have added the fix for “Exporting throws script error for columns without field”  issue.

Please let us know if you have any queries.

Regards,   
Pavithra S.
