### ISSUE TITLE
How to package after making some changes? `build` does not dist

### ISSUE THREAD

**Issue by uptonking** [syncfusion/ej2-grids#8]
I made several changes to your code. So I need to compile. 
  
but `npm run build`  doesn't generate a `./dist` directory with `ej2-grids.min.js` file  in it.

any help?

**Comment by isuriya-r39** [comment]
find the below steps to generate grid.min.js file.

File Name | Content
-- | --
package.json | Add the following dependencies in “devDependencies”       "rollup":   "0.52.3",   "rollup-plugin-commonjs":   "^8.2.6",   "rollup-plugin-node-resolve":   "^3.0.0",   "rollup-plugin-sourcemaps":   "^0.4.2",   "rollup-plugin-uglify":   "^2.0.1"
gulpfile.js | Add the following code snippet in gulpfile.js       For minified scripts, set ‘minified’(marked bold) variable as   true and for un minified scripts set ‘minified’ variable as   false.       var   rollup = require("rollup");   var   rollupUglify = require("rollup-plugin-uglify");   var   rollupCommonjs = require("rollup-plugin-commonjs");   var   rollupResolve = require("rollup-plugin-node-resolve");   var   rollupSourcemaps = require("rollup-plugin-sourcemaps");       gulp.task('bundle',   async function () {         var minified = false;         var plugins = [             rollupCommonjs(),             rollupResolve()         ];             if (minified) {             plugins.push(rollupSourcemaps());             plugins.push(rollupUglify());         }         var writeObj = {             name: "ej",             file: "package/ej2-grids" + (minified ? '.min' : '') +   ".js",             format: "iife",             sourcemap: minified         };         var bundleObj = {             input: "./script.js",             plugins: plugins         };             var bundle = await rollup.rollup(bundleObj);         await bundle.write(writeObj);   });
script.js | Create new file named ‘script.js’ in Grid Package   Repository for which scripts are to be bundled, with the following code.       import   * as grids from './src';       grids.Grid.Inject(grids.Filter,   grids.Page, grids.Selection, grids.Sort, grids.Group, grids.Reorder,   grids.RowDD, grids.DetailRow, grids.Toolbar, grids.CommandColumn,   grids.Aggregate, grids.Search, grids.VirtualScroll, grids.Edit,   grids.ColumnChooser, grids.Resize, grids.ExcelExport, grids.PdfExport,   grids.ContextMenu, grids.Freeze, grids.ColumnMenu, grids.ForeignKey);       export   { grids };
  |  
Tsconfig.json | Change the module name as “es6”       "compilerOptions": {       "target": "es5",       "module": "es6"       . . . . . . .    }


After making the above mentioned changes, run gulp scripts and then gulp bundle to generate the bundled global scripts for grid package in directory “package/”.

**Comment by uptonking** [comment]
good job. I have built it successfully
